# version: '3.8'

services:
  #Service Web PHP Apache
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mediastock-web
    ports:
      - "4433:80"
    volumes:
      - ./public:/var/www/html/public
      - ./src:/var/www/html/src
      - ./config:/var/www/html/config
      - ./vendor:/var/www/html/vendor
      - ./composer.json:/var/www/html/composer.json
      - ./composer.lock:/var/www/html/composer.lock
      - ./sql:/var/www/html/sql

    environment:
      DB_HOST: mysql
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
    depends_on:
      - mysql
    networks:
      - mediastock-network

  # Service Base de Données MySQL
  mysql:
    image: mysql:8.0
    container_name: mediastock-db
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      TZ: Europe/Paris
    command: >
      --default-authentication-plugin=mysql_native_password
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_unicode_ci
    volumes:
      - mysql-data:/var/lib/mysql
      - ./sql:/docker-entrypoint-initdb.d:ro
    networks:
      - mediastock-network

  # Service phpMyAdmin
  phpmyadmin:
    image: phpmyadmin:latest
    container_name: mediastock-phpmyadmin
    ports:
      - "9081:80"
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
    depends_on:
      - mysql
    networks:
      - mediastock-network

volumes:
  mysql-data:

networks:
  mediastock-network:
    driver: bridge
