Insert INTO `Item`(`nom`, `model`, `qr_code`, `image_url`, `etat`, `categorie_id`) VALUES
('PC Portable', 'DELL','1','fa-solid fa-desktop','moyen','1'),
-- ('PC Portable', 'DELL','2','fa-solid fa-laptop','moyen','1'),
('Apple TV', 'MAC','3','fa-solid fa-desktop','bon','1'),
('Micro cravate', 'QHOT','4','fa-solid fa-volume-high','bon','2'),
('Micro cravate', 'QHOT','5','fa-solid fa-volume-high','bon','2'),
('Micro cravate', 'QHOT','6','fa-solid fa-volume-high','bon','2'),
('Micro cravate', 'QHOT','7','fa-solid fa-volume-high','bon','2'),
('Micro cravate', 'QHOT','8','fa-solid fa-volume-high','bon','2'),
('Micro cravate', 'QHOT','9','fa-solid fa-volume-high','bon','2'),
('Micro cravate', 'QHOT','10','fa-solid fa-volume-high','bon','2'),
('Micro cravate', 'QHOT','11','fa-solid fa-volume-high','bon','2'),
('Micro cravate', 'QHOT','12','fa-solid fa-volume-high','bon','2'),
('Micro cravate', '','13','fa-solid fa-volume-high','bon','2'),
('Micro cravate', '','14','fa-solid fa-volume-high','bon','2'),
('Micro cravate', '','15','fa-solid fa-volume-high','bon','2'),
('Micro cravate', '','16','fa-solid fa-volume-high','bon','2'),
('Micro cravate', '','17','fa-solid fa-volume-high','bon','2'),
('Micro', 'SENNHEISER','18','fa-solid fa-volume-high','bon','2'),
('Micro', 'SENNHEISER','19','fa-solid fa-volume-high','bon','2'),
('Micro', 'SENNHEISER','20','fa-solid fa-volume-high','bon','2'),
('Table de mixage ALTO', 'LIVE 1202','21','fa-solid fa-volume-high','bon','2'),
('Caisse de basses', 'THE BOX','22','fa-solid fa-volume-high','bon','2'),
('Enceinte', 'THE BOX','23','fa-solid fa-volume-high','bon','2'),
('Enceinte', 'THE BOX','24','fa-solid fa-volume-high','bon','2'),
('Transmetteur ', 'SENNHEISER','25','fa-solid fa-volume-high','bon','2'),
('Transmetteur ', 'SENNHEISER','26','fa-solid fa-volume-high','bon','2'),
('Transmetteur ', 'SENNHEISER','27','fa-solid fa-volume-high','bon','2'),
('Transmetteur ', 'SENNHEISER','28','fa-solid fa-volume-high','bon','2'),
('Transmetteur ', 'SENNHEISER','29','fa-solid fa-volume-high','bon','2'),
('Casque micro', 'Jabra','30','fa-solid fa-volume-high','bon','2'),
('Casque micro', 'JCV','31','fa-solid fa-volume-high','bon','2'),
('Multiprise','9 trou','32','fa-solid fa-plug','moyen','3'),
('Multiprise','9 trou','33','fa-solid fa-plug','moyen','3'),
('Multiprise','9 trou','34','fa-solid fa-plug','mauvais','3'),
('Multiprise','4 trou','35','fa-solid fa-plug','moyen','3'),
('Multiprise','3 trou','36','fa-solid fa-plug','bon','3'),
('Multiprise','3 trou','37','fa-solid fa-plug','bon','3'),
('Ralonge','noire','38','fa-solid fa-plug','bon','3'),
('Ralonge','blanche','39','fa-solid fa-plug','bon','3'),
('Adaptateur','QDOS USB-C to USBs','40','fa-solid fa-plug','mauvais','3'),
('Adaptateur','UGREEN USB-C to USBs','41','fa-solid fa-plug','bon','3'),
('Adaptateur','SELORE USB-C to USBs','42','fa-solid fa-plug','bon','3'),
('Adaptateur','SELORE USB to USB-C','43','fa-solid fa-plug','bon','3'),
-- ('Adaptateur','ACEELE USB to HDMI','44','fa-solid fa-plug','bon','3'),
('Adaptateur','SYNCWIRE USB to RJ45','45','fa-solid fa-plug','bon','3'),
('Adaptateur','USB-C to USB','46','fa-solid fa-plug','bon','3'),
('Adaptateur','ThunderBolt to VGA','47','fa-solid fa-plug','bon','3'),
('Adaptateur','ThunderBolt to VGA','48','fa-solid fa-plug','bon','3'),
('Adaptateur','ThunderBolt to VGA','49','fa-solid fa-plug','bon','3'),
('Adaptateur','ThunderBolt to VGA','50','fa-solid fa-plug','bon','3'),
('Adaptateur','ThunderBolt to VGA','51','fa-solid fa-plug','bon','3'),
('Adaptateur','ThunderBolt to VGA','52','fa-solid fa-plug','bon','3'),
('Chargeur AC','ASUS','53','fa-solid fa-plug','bon','3'),
('Chargeur AC','ASUS','54','fa-solid fa-plug','bon','3'),
('Cable HDMI','','55','fa-solid fa-plug','bon','3'),
('Cable HDMI','','56','fa-solid fa-plug','bon','3'),
('Cable HDMI','','57','fa-solid fa-plug','bon','3'),
('Cable HDMI','','58','fa-solid fa-plug','bon','3'),
('Cable HDMI','','59','fa-solid fa-plug','bon','3'),
('Cable HDMI','','60','fa-solid fa-plug','bon','3'),
('Cable HDMI','','61','fa-solid fa-plug','bon','3'),
('Enceinte Portable','Fenton','62','fa-solid fa-volume-high','bon','2'),
('Micro','Fenton','63','fa-solid fa-volume-high','bon','2');
